### ISSUE TITLE
Create new data set with Census building permits

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/Census#11]
Read file **L:\Libraries\Census\Raw\Permits\permits2000_2017.csv** and create a new permanent SAS data set from it. Add this data set to the DCData metadata.

**Comment by ptatian** [comment]
@maggiesu0725 Would you be able to help with this? It is needed for the regional housing framework. I may have some other tasks as well but can check with you later about those.

I neglected to say in my instructions above that this file has all permits for the US and we should only keep those in the Washington MSA in the final data set. 

Documentation of the permits data can be found in the **L:\Libraries\Census\Doc\Permits** folder. 

Please let me know if you have questions or don't think you will be able to help. Thanks! cc: @rpitingolo @lhendey

**Comment by maggiesu0725** [comment]
Thanks, don't have time today but will take a look tomorrow. ! @ptatian

**Comment by ptatian** [comment]
@maggiesu0725 That’s great. Thanks!

**Comment by ptatian** [comment]
@maggiesu0725 You can look at **Prog\2010\Blk_xwalk_2000_2010_md.sas** in this repo as a model of how to create a new permanent data set. (Don't look at the DC version of this program as that is outdated.) Let me know if you have any questions.

**Comment by ptatian** [comment]
@maggiesu0725 You can use the *$ctym15f.* format to assign 5-digit county codes to MSA codes. For example,

```
if put( county, $ctym15f. ) = '47900';
```

Will select all obs in the Washington MSA.

**Comment by maggiesu0725** [comment]
batched submitted. L:\Libraries\Census\Prog\Read_2000_2017_buildingpermits.log
